# -*- coding: utf-8 -*-
"""heart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SesFecxefhRLd90eiFJgj6heIMRAiYVY
"""

import pandas as pd

df = pd.read_csv('/content/heart.csv')
df.head()

df.isnull().sum()

X = df.drop('target', axis=1)
y = df['target']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)
rf.fit(X_train, y_train)

from xgboost import XGBClassifier

xgb = XGBClassifier(
    eval_metric='logloss',
    random_state=42
)
xgb.fit(X_train, y_train)

from sklearn.svm import SVC

svm = SVC(
    probability=True,
    random_state=42
)
svm.fit(X_train, y_train)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(
    hidden_layer_sizes=(100,50),
    max_iter=1000,
    random_state=42
)
mlp.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

from sklearn.metrics import *

def evaluate_model(model, X_test, y_test):

    y_pred = model.predict(X_test)

    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:,1]
    else:
        y_prob = model.decision_function(X_test)

    return {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "ROC AUC": roc_auc_score(y_test, y_prob)
    }

results = pd.DataFrame({
    "Logistic Regression": evaluate_model(lr,X_test,y_test),
    "Random Forest": evaluate_model(rf,X_test,y_test),
    "XGBoost": evaluate_model(xgb,X_test,y_test),
    "SVM": evaluate_model(svm,X_test,y_test),
    "KNN": evaluate_model(knn,X_test,y_test),
    "MLP": evaluate_model(mlp,X_test,y_test)
})

results.T

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, rf.predict(X_test))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Random Forest Confusion Matrix")
plt.show()

