# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oLgfM-x9xyuFpasCl_mA6fdiFxNG-QJ
"""

import pandas as pd
import seaborn as sns

data = pd.read_csv("/content/voice.csv")

print(data.head())

print("\nRows and Columns:")
print(data.shape)

print(data.tail())

print(data.describe())

print(data.info())

print(data.isnull().sum())

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.heatmap(data.drop('label', axis=1).corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x='label', data=data, palette='viridis')
plt.title('Distribution of Gender Labels')
plt.xlabel('Label')
plt.ylabel('Count')
plt.show()

from sklearn.preprocessing import LabelEncoder

X = data.drop("label", axis=1)

y = data["label"]

encoder = LabelEncoder()

y = encoder.fit_transform(y)

print(y[:10])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print(predictions[:10])

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

import joblib

joblib.dump(model, "gender_model.pkl")

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

some_features = X_test.iloc[0].values.tolist()
result = model.predict([some_features])

print("Predicted Gender:", result)

# Install required libraries
!pip install gradio joblib scikit-learn pandas numpy -q

# Import libraries
import pandas as pd
import numpy as np
import joblib
import gradio as gr

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# -------------------------------
# Load Dataset
# -------------------------------

data = pd.read_csv("/content/voice.csv")

# Features and Target
X = data.drop("label", axis=1)
y = data["label"]

# Encode labels
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# -------------------------------
# Train Model
# -------------------------------

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# Accuracy
predictions = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    predictions
)

print("Model Accuracy:", accuracy)

# Save model
joblib.dump(model, "gender_model.pkl")

# -------------------------------
# AI Agent Function
# -------------------------------

feature_names = list(X.columns)

def predict_gender(*inputs):

    values = np.array(inputs).reshape(1, -1)

    prediction = model.predict(values)[0]

    if prediction == 1:
        gender = "Male"
    else:
        gender = "Female"

    report = f"""
    Gender Recognition Report

    Predicted Gender: {gender}

    Model Accuracy: {accuracy:.2%}

    Analysis:
    Prediction completed successfully.
    """

    return report

# -------------------------------
# Gradio Interface
# -------------------------------

inputs = []

for col in feature_names:

    inputs.append(
        gr.Number(
            label=col
        )
    )

demo = gr.Interface(
    fn=predict_gender,
    inputs=inputs,
    outputs=gr.Textbox(
        label="Prediction Report"
    ),
    title="Speech-Based Gender Recognition Agent",
    description="""
    Enter all voice feature values and click Submit.
    The AI Agent predicts the speaker gender and generates a report.
    """
)

demo.launch(share=True)